name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            name: aarch64-macos
          - os: ubuntu-latest
            name: x86_64-linux
          - os: ubuntu-24.04-arm
            name: aarch64-linux
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install zig
        uses: montanaflynn/setup-zig@main
        with:
          version: 0.15.2

      - name: build
        run: zig build

      - name: test
        run: zig build test
